apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: xiamimate
    user: xiamimate
    isDefault: true
    jsonData:
      sslmode: disable
      postgresVersion: 1600
    secureJsonData:
      password: xiamimate
